language: c
addons:
  apt:
    sources:
      - avsm
    packages:
      - ocaml
      - opam
      - aspcud
env:
  matrix:
    - MODE=build COQ_VERSION=8.5.3
    - MODE=build COQ_VERSION=8.6
    - MODE=lockserv COQ_VERSION=8.6 OPAMBUILDTEST=1
    - MODE=lockserv-seqnum COQ_VERSION=8.6
    - MODE=lockserv-serialized COQ_VERSION=8.6
script: bash -ex .travis-ci.sh
sudo: false
notifications:
  email: false
